// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("MBrace.Core")]
[assembly: AssemblyProductAttribute("MBrace.Core")]
[assembly: AssemblyCompanyAttribute("Nessos Information Technologies")]
[assembly: AssemblyCopyrightAttribute("© Nessos Information Technologies.")]
[assembly: AssemblyTrademarkAttribute("MBrace")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
    }
}
