image: Visual Studio 2019
init:
  - git config --global core.autocrlf input

build_script:
  - cmd: build.cmd -e IgnoreClusterTests=true

test: off

version: '{build}'

artifacts:
  - path: artifacts\*.nupkg
