image: Visual Studio 2019
init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd -e TestCoverage=unit,smoke
test: off
version: '{build}'
artifacts:
  - path: artifacts
    name: artifacts

on_finish:
  - ps: >-
      $wc = New-Object 'System.Net.WebClient';
      Foreach ($file in Get-ChildItem './testResults/*.trx') {
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", $file.FullName)
      }