// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyProductAttribute("MBrace")>]
[<assembly: AssemblyCompanyAttribute("Nessos Information Technologies")>]
[<assembly: AssemblyCopyrightAttribute("© Nessos Information Technologies.")>]
[<assembly: AssemblyTrademarkAttribute("MBrace")>]
[<assembly: AssemblyVersionAttribute("1.5.4")>]
[<assembly: AssemblyFileVersionAttribute("1.5.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyProduct = "MBrace"
    let [<Literal>] AssemblyCompany = "Nessos Information Technologies"
    let [<Literal>] AssemblyCopyright = "© Nessos Information Technologies."
    let [<Literal>] AssemblyTrademark = "MBrace"
    let [<Literal>] AssemblyVersion = "1.5.4"
    let [<Literal>] AssemblyFileVersion = "1.5.4"
