// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("MBrace")]
[assembly: AssemblyCompanyAttribute("Nessos Information Technologies")]
[assembly: AssemblyCopyrightAttribute("© Nessos Information Technologies.")]
[assembly: AssemblyTrademarkAttribute("MBrace")]
[assembly: AssemblyVersionAttribute("1.0.12")]
[assembly: AssemblyFileVersionAttribute("1.0.12")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.12";
    }
}
